version: '3'

services:
  app_test:
    build:
      context: .
      dockerfile: ./docker/app.dockerfile.test
    ports:
      - 8080:8080
    volumes:
      - .:/golang-docker-todo
    depends_on:
      - database_test
    container_name: golang-docker-app_test
    networks:
      - golang-docker-todo_test

  database_test:
    build: 
      context: .
      dockerfile: ./docker/db.dockerfile
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: golang-docker-todo_test
      DATABASE_HOST: database
      DB_DRIVER: mysql 
    container_name: golang-docker-db_test
    ports:
      - 3306:3306
    volumes:
      - golang-docker-data_test:/var/lib/mysql
    networks:
      - golang-docker-todo_test


# persisted storage
volumes:
  golang-docker-data_test:

networks:
  golang-docker-todo_test:
    driver: bridge
